### ISSUE TITLE
boolM

### ISSUE THREAD

**Issue by andrewthad** [mokus0/monad-loops#14]
In `base`, there is a module `Data.Bool` that exports a function named `bool`. I'd like to add a monadic version of that function (and call it `boolM`). It doesn't totally fit the theme of `monad-loops`, since it doesn't do any looping, but it's a function I often need.

**Comment by mokus0** [comment]
I'm not categorically against it, but I'd be a little hesitant to include it in this particular library since as you mentioned it doesn't actually do any kind of looping.  Given the argument order of Data.Bool.bool, have you considered something like `bool x y =<< action`?

**Comment by andrewthad** [comment]
That's a good point. The `bool x y =<< action` construction is better (and has a more general type) than what I was thinking about.
